# Site settings
title: Sorta Insightful
description: > # this means to ignore newlines until "baseurl:"
  In a world where everyone has opinions, one man...also has opinions
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.alexirpan.com" # the base hostname & protocol for your site
github_username:  alexirpan
timezone: "America/Los_Angeles"

gems: [jekyll-paginate]

paginate: 3

# Get around Jekyll default ordering and requirement to have
# a page for all header links. Hardcoded + repeated but not
# worth doing it right at this time
header_links:
    - url: "/recs/"
      title: "Reviews"
    - url: "/projects/"
      title: "Projects"
    - url: "/puzzles/"
      title: "Puzzles"
    - url: "/archive/"
      title: "Archive"
    - url: "/research/"
      title: "Research"
    - url: "/about/"
      title: "About"
    - url: "/feed.xml"
      image: /public/feed-icon.png


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    math_engine: mathjax
